export const SET_IS_MOBILE = 'base/SET_IS_MOBILE'
export const SET_SCREEN_WIDTH = 'base/SET_SCREEN_WIDTH'
export const SET_SCREEN_HEIGHT = 'base/SET_SCREEN_HEIGHT'
export const SET_MENU_TABS = 'base/SET_MENU_TABS'
export const SET_MENU_ACTIVE = 'base/SET_MENU_ACTIVE'
